source 'https://github.com/CocoaPods/Specs.git'

workspace '../GranadaLayout'
xcodeproj 'Example.xcodeproj'

target "Example" do
  pod "GranadaLayout", :path => "../GranadaLayout.podspec"
end

target "Tests" do
  pod 'Expecta', '~> 0.3.1'
  pod 'FBSnapshotTestCase'
end

require 'slather'
Slather.prepare_pods(self)
