source 'https://github.com/CocoaPods/Specs.git'

workspace '../GranadaLayout'
xcodeproj 'Example.xcodeproj'

target "Example" do
  pod "GranadaLayout", :path => "../GranadaLayout.podspec"
end

target "Tests" do
  pod 'Expecta', '~> 1.0'
  pod 'FBSnapshotTestCase', '1.7'
end

require 'slather'
